---
- name: restart postgresql
  service:
    name: "{{ postgresql_service_name }}"
    state: restarted
#   shell: 
#     cmd: pg_ctlcluster {{ postgresql_version }} {{ postgresql_cluster_name }} restart
#     executable: /bin/bash
  become: yes
#   become_user: "{{ postgresql_service_user }}"

- name: restart repmgr
  service:
    name: repmgrd
    state: restarted
  become: yes
